language: python
python:
  - "3.7"
  - "3.8"
  
os: linux
arch:
  - amd64
  - arm64
  
install:
  - pip install coverage
  - pip install pypack

script:
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
